# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Package TSC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --output publish/
      if: ${{ always() }}
    - name: Publish TSC Build
      uses: actions/upload-artifact@v4
      with:
        name: TSC-Build-${{ github.run_number }}-${{ matrix.os }}
        path: |
          publish/TSC.AvaloniaUI*
          !publish/**/*.dll
          !publish/**/*.json
          !publish/**/*.pdb
